# Generated by Django 2.2 on 2021-05-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDetails',
        ),
    ]
