# Generated by Django 2.2 on 2021-05-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetails',
            name='img',
        ),
    ]
